export const TIMER_TICK_MS = 1_000

export const MATCH_SEARCH_TIMEOUT_MS = 5_000
export const MATCH_SEARCH_POLL_INTERVAL_MS = 1_000
export const AI_MATCH_DELAY_MS = 1_500

export const START_CHALLENGE_DURATION_MS = 2_000
export const ROUND_TITLE_DURATION_MS = 2_000
export const QUESTION_PREVIEW_DURATION_MS = 3_000
export const ROUND_READY_TIMEOUT_MS = 30_000
export const ROUND_READY_POLL_INTERVAL_MS = 500
export const ROUND_RESULT_DURATION_MS = 3_000

export const ROUND_SYNC_MIN_DELAY_MS = 1_000
export const ROUND_SYNC_MAX_DELAY_MS = 3_000
export const ANSWER_REVEAL_DURATION_MS = 5_000

export const REMATCH_RESULT_DELAY_MS = 2_000

export const ENTRY_BANNER_TRANSITION_MS = 2_000
export const ENTRY_BANNER_DURATION_MS = 3_600

export const LOGIN_CLOUDS_DELAY_MS = 100
export const LOGIN_STARS_DELAY_MS = 300
export const LOGIN_FORM_DELAY_MS = 600
export const LOGIN_INPUT_DELAY_MS = 1_200
